
img_dir_train: "/images"
ann_path_train: "/annotations.json"

img_dir_val: "/val/images"
ann_path_val: "/val/annotations.json"


characters: "0123456789.+-E/:" #
special_tokens: ["<SOS>", "<EOS>", "<PAD>","<BLK>"]
max_text_length: 19


img_dir_test: "/test/crop_images/images" #
ann_path_test: "/crop_images/annotations.json" #

